BulkRecords/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'polls'
urlpatterns = [
  path('',views.search,name='top'),
  path('detail/<int:category>/<str:id>', views.detail, name='detail'),
  path('users/<int:pk>/', views.users_detail, name='users_detail'),
  path('save/<int:category>/<str:id>', views.save, name='save'),
  path('login/',auth_views.LoginView.as_view(template_name='polls/login.html'),name='login'),
  path('logout/',auth_views.LogoutView.as_view(),name='logout'),
  path('signup/',views.signup, name='signup'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Save(models.Model):
  title = models.CharField(max_length=150)
  post_id = models.CharField(max_length=150)
  img_url = models.CharField(max_length=150)
  category = models.CharField(max_length=10)
  author = models.CharField(max_length=150)
  post_date = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(User, on_delete = models.CASCADE)
  

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Save
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required


# Create your views here.
from django.http import HttpResponse
import tmdbsimple as tmdb
import spotipy
import sys
import requests
from spotipy.oauth2 import SpotifyClientCredentials
import os
import urllib.parse
RAKUTEN_BOOKS_API_URL = "https://app.rakuten.co.jp/services/api/BooksBook/Search/20170404"
RAKUTEN_APP_ID = '1082042096723903381'
tmdb.API_KEY = '1c8dee5cdaf6294a7c742f5821f4108d'
client_id = 'e6cbdc037d6747dd9988ba6af9939a1c'
client_secret = 'b07e4f608b71411cb089d1d081aaf7ff'
client_credentials_manager = spotipy.oauth2.SpotifyClientCredentials(client_id, client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

# Create your views here.

def search(request):
  if 'movie_query' in request.GET:
    keyword = str(request.GET.get('movie_query', ''))
    if keyword != '':
      search = tmdb.Search()
      response = search.movie(query=keyword)
      responses = search.results
      for i in range(len(responses)):
        responses[i]['category'] = 1

    else:
      responses = {}
    return render(request, 'polls/top.html',{'responses':responses})
  elif 'music_query' in request.GET:
    keyword = str(request.GET.get('music_query',''))
    if keyword != '':
      response = sp.search(q=keyword, limit=50, offset=10, type='album', market=None)
      responses = []
      for album in response['albums']['items']:
        result = {'title':album['name'],'release_date':album['release_date'],'id':album['id']}
        for artist in album['artists']:
          result['artist_name'] = artist['name']
        images = album['images'][0]
        result['image'] = images['url']
        result['category'] = 2
        responses.append(result)
    else:
      responses = {}
    return render(request, 'polls/top.html',{'responses':responses})
  elif 'book_query' in request.GET:
    keyword = str(request.GET.get('book_query',''))
    keyword_quote = urllib.parse.quote(keyword)
    if keyword != '':
      response = requests.get('{}?format=json&title={}&booksGenreId=001004008&hits=10&applicationId={}'.format(RAKUTEN_BOOKS_API_URL,keyword_quote,RAKUTEN_APP_ID))
      responses=[]
      for i in range(int(response.json()["hits"])):
          title = response.json()["Items"][i]["Item"]['title']
          author = response.json()["Items"][i]["Item"]['author']
          image = response.json()["Items"][i]["Item"]['mediumImageUrl']
          id = response.json()["Items"][i]["Item"]['isbn']
          result = {'title':title,'author':author,'image':image,'id':id}
          result['category'] = 3
          responses.append(result)
    else:
      responses = {}
    return render(request, 'polls/top.html',{'responses':responses})

  else:
      responses = Save.objects.all().order_by('-post_date')[:14]
      return render(request, 'polls/top.html',{'responses':responses})

@login_required
def detail(request, category=None, id=None):
  #category 1=movie 2=music 3=book
  user = request.user
  saved_user = Save.objects.filter(post_id = id)
  saved_or = {}
  save_item = Save.objects.filter(post_id=id,user=user)
  if save_item.count() > 0:
    saved_or['saved'] = 0
  else:
    saved_or['saved'] = 1

  if category == 1:
    movie = tmdb.Movies(id)
    responses = movie.info()
    responses['category'] = category
    responses['category_name'] = 'Movie'
    crew = movie.credits()['crew'][0]
    author = crew['name']
    trailers = list(filter(lambda v: v['type'] == 'Trailer' or v['type'] == 'Teaser' , movie.videos()['results']))
    trailer = trailers[0]
    return render(request, 'polls/detail.html',{'responses':responses,'trailer':trailer,'author':author,'saved_or':saved_or,'saved_user':saved_user})

  elif category == 2:
    responses = sp.album('spotify:album:'+id)
    responses['category'] = category
    responses['category_name'] = 'Music'
    responses['image'] = responses['images'][0]['url']
    artist = {}
    for i in responses['artists']:
      artist['artist_name'] = i['name']
      artist['artist_id'] = i['id']
      
    tracks = []
    for track in responses['tracks']['items']:
      hoge = {}
      hoge['track_name'] = track['name']
      external_urls = track['external_urls']
      hoge['track_url'] = external_urls['spotify']
      tracks.append(hoge)
    return render(request, 'polls/detail.html',{'responses':responses,'artist':artist,'tracks':tracks,'saved_or':saved_or,'saved_user':saved_user})
  elif category == 3:
    detail_id = int(id)
    response = requests.get('{}?format=json&isbn={}&applicationId={}'.format(RAKUTEN_BOOKS_API_URL,detail_id,RAKUTEN_APP_ID))    
    responses = []
    for i in range(int(response.json()["hits"])):
        title = response.json()["Items"][i]["Item"]['title']
        author = response.json()["Items"][i]["Item"]['author']
        image = response.json()["Items"][i]["Item"]['mediumImageUrl']
        release_date = response.json()["Items"][i]["Item"]['salesDate']
        caption = response.json()["Items"][i]["Item"]['itemCaption']
        responses = {'title':title,'id':id,'author':author,'image':image,'release_date':release_date,'caption':caption,'category':category,'category_name':'Book'}
        return render(request, 'polls/detail.html',{'responses':responses,'saved_or':saved_or,'saved_user':saved_user})
    #book=9784101355511,movie=149,music=5ng5dilD1OOQkeON0kpaxd
    
def users_detail(request, pk):
  user = get_object_or_404(User, pk=pk)
  saved = user.save_set.all().order_by('-post_date')
  return render(request, 'polls/users_detail.html',{'user':user,'saved':saved})

def signup(request):
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      new_user = form.save()
      input_username = form.cleaned_data['username']
      input_password = form.cleaned_data['password1']
      new_user = authenticate(username=input_username,password=input_password)
      if new_user is not None:
        login(request, new_user)
        return redirect('polls:users_detail', pk=new_user.pk)
  else:
    form = UserCreationForm()
  return render(request, 'polls/signup.html',{'form':form})

@login_required
def save(request, category=None, id=None):
  user = request.user
  save_item = Save.objects.filter(post_id=id,user=user)
  if save_item.count() > 0:
    save_item.delete()
    return redirect('polls:users_detail', pk=request.user.pk)
  else:  
    if category == 1:
      movie = tmdb.Movies(id)
      responses = movie.info()
      title = responses['title']
      img_url = responses['poster_path']
      crew = movie.credits()['crew'][0]
      author = crew['name']
      t = Save(title = title,post_id = id,img_url = 'http://image.tmdb.org/t/p/w185/'+img_url,category = 1,author = author,user = request.user)
      t.save()
      return redirect('polls:users_detail', pk=request.user.pk)

    elif category == 2:
      responses = sp.album('spotify:album:'+id)
      artist = {}
      title = responses['name']
      img_url = responses['images'][0]['url']
      artist = {}
      for i in responses['artists']:
        artist['artist_name'] = i['name']
      author = artist['artist_name']
      t = Save(title = title,post_id = id,img_url = img_url,category = 2,author = author,user = request.user)
      t.save()
      return redirect('polls:users_detail', pk=request.user.pk)

    elif category == 3:
      detail_id = int(id)
      response = requests.get('{}?format=json&isbn={}&applicationId={}'.format(RAKUTEN_BOOKS_API_URL,detail_id,RAKUTEN_APP_ID))    
      for i in range(int(response.json()["hits"])):
          title = response.json()["Items"][i]["Item"]['title']
          author = response.json()["Items"][i]["Item"]['author']
          img_url = response.json()["Items"][i]["Item"]['mediumImageUrl']
          t = Save(title = title,post_id = id,img_url = img_url,category = 3,author = author,user = request.user)
          t.save()
          return redirect('polls:users_detail', pk=request.user.pk)

polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>BulkRecord</title>
</head>
<body>
    <header>
        <h2 class='logo'><a href="/">BulkRecord</a></h2>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/color/jquery.color-2.2.0.min.js" integrity="sha256-aSe2ZC5QeunlL/w/7PsVKmV+fa0eDbmybn/ptsKHR6I=" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% load static %}

{% block content %}
  <!-- category別に条件分岐でレイアウト変更-->
  <div class='detail'>
    <section class='detail-1'>
      {% if responses.category == 1 %}
        <span><img src="{% static 'images/movie.svg' %}" alt=""></span>
      {% elif responses.category == 2 %}
        <span><img src="{% static 'images/music.svg' %}" alt=""></span>
      {% elif responses.category == 3 %}
        <span><img src="{% static 'images/book.svg' %}" alt=""></span>
      {% endif %}
    </section>

    <section class='detail-2'>
      <h2 class='detail-title'>{{ responses.title }}{{ responses.name }}</h2>
      <h3>-{{ artist.artist_name }}{{ author }}{{ responses.author }}-</h3>
    </section>

    <section class='detail-3'>
      <div class='detail-img'>
        {% if responses.poster_path %}
          <img src="http://image.tmdb.org/t/p/w185/{{ responses.poster_path }}" alt="" >
        {% elif responses.image %}
          <img src="{{ responses.image }}" alt="" width="20%" >        
        {% else %}
          <img src="/media/image/noimage_movie 1.jpg" alt="" width="20%" >
        {% endif %}
      </div>
      <div class='detail-cont'>
        <div class='detail-cont-1'>
          {% if responses.category == 1 %}
            <p>{{ responses.overview }}</p>
            <iframe src="https://www.youtube.com/embed/{{ trailer.key }}" frameborder="0"></iframe>
          {% elif responses.category == 2 %}
            <section class='tracks'>
              {% for s in tracks %}
                <br><span>{{ forloop.counter }}.&nbsp;</span>
                <a href="{{ s.track_url }}">
                  {{ s.track_name }}
                  <img src="{% static 'images/spotify.svg' %}" alt="" class='spotify'>
                </a>
              {% endfor %}
            </section>
          {% elif responses.category == 3 %}
            <p>{{ responses.caption }}</p>
          {% endif %}
        </div>
        <div class='detail-cont-2'>
          {% if saved_or.saved == 0 %}
            <span class='remove-button'><a href="{% url 'polls:save' responses.category responses.id %}">My Pageから削除する</a></span>
          {% else %}
            <span class='save-button'><a href="{% url 'polls:save' responses.category responses.id %}">My Pageに保存する</a></span>        
          {% endif %}
          <h2 class='saved-count'>{{ saved_user|length }}</h2>
          <h4 id='saved'>saved</h4>
          {% for i in saved_user %}
            <h2 class='saved-user'><a href="{% url 'polls:users_detail' i.user_id %}"><img src="{% static 'images/user.svg' %}" alt="" class='saved-user-icon'>&nbsp;{{ i.user }} <img src="{% static 'images/arrow.svg' %}" alt="" class='saved-user-button'> </a></h2>        
          {% endfor %}
        </div>
      </div>
    </section>

  </div>
{% endblock %}

polls/templates/polls/login.html
{% extends 'polls/base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value='ログイン'>
  </form>
{% endblock %}

polls/templates/polls/signup.html
{% extends 'polls/base.html' %}

{% block content %}
<h2>ユーザー登録</h2>

<form action="{% url 'polls:signup' %}" method='post'>{% csrf_token %}
  <label>ユーザー名</label>
  {{ form.username }}
  {{ form.username.errors }}
  <br>
  <label>パスワード</label>
  {{ form.password1 }}
  {{ form.password1.errors }}
  <br>
  <label>パスワード確認</label>
  {{ form.password2 }}
  {{ form.password2.errors }}
  <br>
  <input type="submit" value='登録'>
</form>

<p><a href="{% url 'polls:login' %}">ログイン</a></p>
{% endblock %}

polls/templates/polls/top.html
{% extends 'polls/base.html' %}
{% load static %}

{% block content %}
  <div class='top-content'>
      <div class='navi'>
          {% if request.user.is_authenticated %}
            <br>
            <a href="{% url 'polls:users_detail' request.user.id %}">マイページ</a>
            <span>|</span>
            <a href="{% url 'polls:logout' %}">ログアウト</a>
          {% else %}
            <a href="{% url 'polls:login' %}">ログイン</a>
          {% endif %}
        </div>
    <div class='search-form'>
      <div class='search-item'>
        <span><img src="{% static 'images/movie.svg' %}" alt=""></span>
        <form action="" method="GET">
          <input type="text" name="movie_query" placeholder="movie">
        </form>
      </div>
      <div class='search-item'>
        <span><img src="{% static 'images/music.svg' %}" alt=""></span>
        <form action="" method="GET">
          <input type="text" name="music_query" placeholder="music">
        </form>       
      </div>
      <div class='search-item'>
        <span><img src="{% static 'images/book.svg' %}" alt=""></span>
        <form action="" method="GET">
          <input type="text" name="book_query" placeholder="book">
        </form>
      </div>
    </div>
    
      <div class='result-contents right-content grid'>
      {% for s in responses %}
        <div class='result-content grid-item'>
          <!--<a href="{% url 'polls:detail' s.category s.id %}" class='detail-button'>{{ s.title }}</a>-->
          {% if s.artist_name %}
            <!--<p>artist:{{ s.artist_name }}</p>-->
          {% endif %}
          {% if s.author %}
            <!--<p>artist:{{ s.author }}</p>-->
          {% endif %}
            {% if s.poster_path %}
            <a href="{% url 'polls:detail' s.category s.id %}" class='detail-button'>
              <img src="http://image.tmdb.org/t/p/w185/{{ s.poster_path }}" alt="" >
              <span class='caption'>{{ s.title }}</span>
            </a>
            {% elif s.image %}
            <a href="{% url 'polls:detail' s.category s.id %}" class='detail-button'>
              <img src="{{ s.image }}" alt="">
              <span class='caption'>{{ s.title }}</span>
            </a>
            {% elif s.img_url %}
            <a href="{% url 'polls:detail' s.category s.post_id %}" class='detail-button'>
              <img src="{{ s.img_url }}" alt="">
              <span class='caption'>{{ s.title }}</span>
            </a>
            {% else %}
              <img src="/media/image/noimage_movie 1.jpg" alt="">

            {% endif %}
          {% if s.release_date %}
            <!--<p>{{ s.release_date }}</p>-->
          {% endif %}
        </div>
        {% endfor %}
      </div>
  </div>
{% endblock %}

polls/templates/polls/users_detail.html
{% extends 'polls/base.html' %}
{% block content %}
  <div class='user-data'>
    <h2 class='user-name'>{{ user.username }}</h2>
    <h2 class='saved-count'>{{ saved|length }}</h2>
    <h4 id='saved'>saved</h4>
  </div>
  <div class='result-contents grid'>
    {% for s in saved %}
      <div class='result-content grid-item'>
      <a href="{% url 'polls:detail' s.category s.post_id %}" class='detail-button'>
        <img src="{{ s.img_url }}" alt="">
        <span class='caption'>{{ s.title }}<br>{{ s.author }}</span>
      </a>
      </div>
    {% endfor %}
  </div>
{% endblock %}